background_opacity      0.8
font_family             JetBrainsMono Nerd Font
bold_font               JetBrainsMono Nerd Font
italic_font             JetBrainsMono Nerd Font
bold_italic_font        JetBrainsMono Nerd Font
font_size               9.8
cursor_shape            beam
cursor_blink_interval   -0
enable_audio_bell       no
term                    xterm-256color
