conky.config = {
    alignment = 'middle_right',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'gray',
    default_outline_color = 'white',
    default_shade_color = 'white',
    color1 = '#ED4E59',
    color2 = '#a048fe',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'JetBrainsMono Nerd Font:size=7',
    gap_x = 30,
    gap_y = 30,
    minimum_height = 250,
    minimum_width = 400,
    maximum_width = 400,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_type = 'override',
    own_window_hints ='undecorated,sticky,skip_taskbar,skip_pager,below',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 3.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,

}

conky.text = [[
${color2}${goto 0}${font ConkySymbols:size=20}t${font} ${voffset -10}Arch Linux» $hr ${color}

${color1}${goto 35}OS               : ${color}${execi 86400 cat `ls -atr /etc/*-release | tail -2` | grep "PRETTY_NAME" | cut -d= -f2 |  sed 's/"//g'}
${color1}${goto 35}Kernel           : ${color}$kernel on $machine
${color1}${goto 35}Total package    : ${color}${exec pacman -Q | wc -l}
${color1}${goto 35}Upgrades package : ${color}${exec pacman -Qu | wc -l}

${color2}${goto 0}${font ConkySymbols:size=16}f${font} ${voffset -10} System» $hr${color}

${color1}${goto 35}CPU  : ${color}${freq_g}GHz ${alignr}${cpu}% ${cpubar 4,100}

${color1}${goto 35}RAM  : ${color}$mem/$memmax ${alignr}$memperc% ${membar 4,100}
${color1}${goto 35}SWAP : ${color}$swap/$swapmax $alignr}$swapperc% ${swapbar 4,100}


${color1}${goto 35}Uptime : ${color}$uptime_short ${alignr}${color1}Load  : ${color}${loadavg}


${color2}${goto 0}${font Font Awesome 5 Free Solid:size=17}${font} ${voffset -10} Storage» $hr${color}

${color1}${goto 35}ROOT : ${color}${fs_used /}/${fs_size /} ${alignr}${fs_used_perc /}% ${fs_bar 4,100 /}
${color1}${goto 35}HOME : ${color}${fs_used /home/dizbati}/${fs_size /home/dizbati} ${alignr}${fs_used_perc /home/dizbati}% ${fs_bar 4,100 /home/dizbati}
${goto 35}
${if_running spotify}
    ${color2}${goto 0}${font Font Awesome 5 Brands:size=18}${font} ${voffset -10} Spotify» $hr${color}


    ${color1}${goto 140}Title  : ${color}${execi 3 python ~/.config/conky/scripts/spotify/spotify.py title}
    ${color1}${goto 140}Artist : ${color}${execi 3 python ~/.config/conky/scripts/spotify/spotify.py artist}
    ${color1}${goto 140}Album  : ${color}${execi 3 python ~/.config/conky/scripts/spotify/spotify.py album}

    ${execi 3 python ~/.config/conky/scripts/spotify/spotify.py update_cover > /dev/null}
    ${image ~/.config/conky/scripts/spotify/cover.jpg -p 5, 434 -s 114x114 -f 2}
    
${endif}
${if_match ${execi 4 iwctl station wlan0 show | grep -w connected | wc -l} == 1}
    ${color2}${goto 0}${font Font Awesome 5 Free Solid:size=16}${font} ${voffset -10} WiFi» $hr${color}

    ${color1}${goto 35}Wireless ESSID  : ${color}${wireless_essid wlan0}
    ${color1}${goto 35}Wireless Bitrate: ${color}${wireless_bitrate wlan0}
    ${color1}${goto 35}Wireless Link   : ${color}${wireless_link_bar 4, 100, wlan0}
${endif}



]]
