[colors]
background = #222
background-alt = #444
foreground = #ED4E59
foreground-alt = #a048fe
primary = #ED4E59
secondary = #ED4E59
alert = #bd2c40

[bar/main]
width = 100%
height = 30
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #f00

border-size = 0
border-color = #00000000

module-margin-left = 1
module-margin-right = 2

font-0 = Nova Mono:size=15
font-1 = Font Awesome 5 Free Regular:size=10
font-2 = Font Awesome 5 Free Solid:size=10
font-3 = Font Awesome 5 Brands:size=10
font-4 = siji:pixelsize=9;1

modules-left = i3
modules-center = spotify
modules-right = xkeyboard alsa date

wm-restack = i3

cursor-click = pointer
cursor-scroll = ns-resize

tray-position = right
tray-detached = false
tray-padding = 1
tray-scale = 1.05

tray-maxsize = 14

enable-ipc = false

[module/spotify]
type = custom/script
interval = 3
format-prefix = " "
format = <label>
format-foreground = ${colors.foreground-alt}
exec = python ~/.config/polybar/scripts/spotify.py --trunclen 90

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground}

label-layout = %layout%

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;

ws-icon-default = ♟

label-mode-padding = 2
label-mode-foreground = ${colors.foreground}
label-mode-background = ${colors.background}

label-focused = %icon% %index%
label-focused-foreground = ${colors.foreground-alt}
label-focused-background = ${colors.background}
label-focused-padding = 2

label-unfocused = %icon% %index%
label-unfocused-padding = 2

label-urgent = %icon% %index%
label-urgent-foreground = #ffffff
label-urgent-background = #6A53E6
label-urgent-padding = 2

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

label =  %date% %time%

[module/alsa]
type = internal/alsa

label-volume =  %percentage%%
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
label-muted-foreground = ${colors.foreground-alt}

label-muted =  mute

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = true
bar-volume-indicator = |
bar-volume-indicator-font = 1
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5
